/**
 * `bagdock dev` — Generate wrangler.toml from bagdock.json and start local dev.
 *
 * Reads bagdock.json, generates a deterministic wrangler.toml, and shells out
 * to `npx wrangler dev`. Dev secrets are read from a local `.dev.vars` file
 * (Wrangler convention) so production secrets in Infisical are never exposed.
 */

import { existsSync, writeFileSync } from 'fs'
import { join } from 'path'
import { spawn } from 'child_process'
import chalk from 'chalk'
import { loadBagdockJson } from './config'

interface DevOptions {
  port?: string
}

export async function dev(opts: DevOptions) {
  const cwd = process.cwd()
  const config = loadBagdockJson(cwd)

  if (!config) {
    console.error(chalk.red('No bagdock.json found. Run'), chalk.cyan('bagdock init'), chalk.red('first.'))
    process.exit(1)
  }

  const port = opts.port ?? '8787'

  // Generate wrangler.toml
  const wranglerToml = generateWranglerToml(config, port)
  const wranglerPath = join(cwd, 'wrangler.toml')

  writeFileSync(wranglerPath, wranglerToml)
  console.log(chalk.green('Generated'), chalk.cyan('wrangler.toml'), chalk.green('from bagdock.json'))

  // Ensure .dev.vars hint exists
  const devVarsPath = join(cwd, '.dev.vars')
  if (!existsSync(devVarsPath) && config.env) {
    const hint = Object.entries(config.env)
      .map(([key, meta]) => `# ${meta.description ?? key}${meta.required ? ' (required)' : ''}\n${key}=`)
      .join('\n')
    writeFileSync(devVarsPath, hint + '\n')
    console.log(chalk.yellow('Created .dev.vars template — fill in your local secrets'))
  }

  console.log(chalk.cyan(`\nStarting wrangler dev on port ${port}...\n`))

  // Shell out to wrangler dev
  const child = spawn('npx', ['wrangler', 'dev', '--port', port], {
    cwd,
    stdio: 'inherit',
    shell: true,
  })

  child.on('exit', (code) => {
    process.exit(code ?? 0)
  })
}

function generateWranglerToml(config: ReturnType<typeof loadBagdockJson> & {}, port: string): string {
  const lines: string[] = [
    `# Auto-generated by @bagdock/cli from bagdock.json`,
    `# Do not edit manually — run \`bagdock dev\` to regenerate`,
    ``,
    `name = "${config.slug}"`,
    `main = "${config.main}"`,
    `compatibility_date = "${config.compatibilityDate ?? '2024-09-23'}"`,
    ``,
  ]

  // Merge any custom wrangler overrides
  if (config.wrangler) {
    for (const [key, value] of Object.entries(config.wrangler)) {
      if (typeof value === 'string') {
        lines.push(`${key} = "${value}"`)
      } else if (typeof value === 'boolean' || typeof value === 'number') {
        lines.push(`${key} = ${value}`)
      }
    }
    lines.push('')
  }

  // Environment variable bindings (declared in [vars] for dev, actual values from .dev.vars)
  if (config.env && Object.keys(config.env).length > 0) {
    lines.push(`[vars]`)
    for (const [key, meta] of Object.entries(config.env)) {
      lines.push(`# ${meta.description ?? key}`)
      lines.push(`# ${key} = "" # Loaded from .dev.vars at runtime`)
    }
    lines.push('')
  }

  return lines.join('\n')
}
